{% set name = "steinbock" %}
{% set version = "0.16.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/steinbock-{{ version }}.tar.gz
  sha256: 0c1802a319255914fea00bf3c6bfde79f27ec536637e179d5f582525bfee56fe

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1
  entry_points:
    - steinbock = steinbock._cli:steinbock_cmd_group

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools-scm
  run:
    - anndata
    - click
    - click-log
    - fcswrite
    - h5py
    - imageio
    - networkx
    - numpy
    - opencv
    - pandas
    - python >={{ python_min }}
    - scikit-image
    - scipy
    - tifffile
    - xtiff

test:
  imports:
    - steinbock
  commands:
    - pip list
    - which steinbock  # [not win]
    - where steinbock  # [win]
    # - pip check  # Fails due to opencv-python-headless
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/steinbock
  summary: A toolkit for processing multiplexed tissue images
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/BodenmillerGroup/steinbock

extra:
  recipe-maintainers:
    - goanpeca
    - Milad4849
